version: "2"

linters:
  default: standard

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - (io.Closer).Close
      - (*os.File).Close
      - (net.Conn).Close
      - (net.Listener).Close
