linters:
  default: standard

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Fprint
      - (io.Closer).Close
      - (net.Conn).Close
      - (net.Listener).Close
