FROM golang:1.22 AS builder
WORKDIR /go/src/github.com/openshift/ingress-node-firewall
COPY . .

RUN ./hack/build-daemon.sh

FROM quay.io/centos/centos:stream8
COPY --from=builder /go/src/github.com/openshift/ingress-node-firewall/bin/daemon /usr/bin/
COPY --from=builder /go/src/github.com/openshift/ingress-node-firewall/bin/syslog /usr/bin/
CMD ["/usr/bin/daemon"]
