resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- env.yaml
- manager_webhook_patch.yaml
images:
- name: controller
  newName: image-registry.openshift-image-registry.svc:5000/openshift-ingress-node-firewall/ingress-node-firewall-controller
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
