# permissions for end users to view ingressnodefirewallnodestates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressnodefirewallnodestate-viewer-role
rules:
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewallnodestates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewallnodestates/status
  verbs:
  - get
