apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-node-firewall-daemon
  namespace: '{{.NameSpace}}'
spec:
  podSelector:
    matchLabels:
      app: ingress-node-firewall-daemon
  policyTypes:
  - Ingress
  - Egress
  # Deny all ingress traffic
  ingress: []
  # Allow all egress traffic
  egress:
  - {}
